### PR TITLE
add profile: imam

### PR DESCRIPTION
**Pull request by imambungo**
TODO: add profile pic

### CODE REVIEW

**Comment by imambungo** [comment]
@ariefrahmansyah is it required to use a square image for the profile picture?

**Comment by ariefrahmansyah** [comment]
> @ariefrahmansyah is it required to use a square image for the profile picture?

Yes, it's required.

**Comment by ariefrahmansyah** [comment]
Hi, any update on this? :)

**Comment by imambungo** [comment]
> Hi, any update on this? :)

Wait kk, fotony masih d kamera kawan :pray:

**Review by ariefrahmansyah — APPROVED** [review]
LGTM!

**Pull request merged**
